import fs from "fs";
import path from "path";
import yaml from "js-yaml";

const SGLANG_DIR = path.join(process.cwd(), "engines", "sglang");
const SGLANG_OVERLAY_DIR = path.join(process.cwd(), "engines", "sglang-overlay");
const SGLANG_GUIDES_DIR = path.join(process.cwd(), "engines", "sglang-guides");

// Deep-merge an overlay onto a base block. Objects merge recursively; scalars and
// arrays are replaced by the overlay. Used to graft fork-local additions (e.g. the
// DeepSeek-V4-Flash PPU hardware) onto an upstream-generated block.
function deepMerge(base, over) {
  if (Array.isArray(over) || typeof over !== "object" || over === null) return over;
  const out = { ...(base && typeof base === "object" && !Array.isArray(base) ? base : {}) };
  for (const [k, v] of Object.entries(over)) {
    if (k === "__proto__" || k === "constructor" || k === "prototype") continue; // prototype-pollution guard
    out[k] = deepMerge(out[k], v);
  }
  return out;
}

/**
 * If an SGLang engine block exists for this recipe, attach an `engines` map +
 * `default_engine` to the recipe (mutates and returns it).
 *
 * Block resolution:
 *   1. engines/sglang/<hf_id>.yaml         — GENERATED by sync-sglang.mjs from the
 *      new SGLang cookbook configs (authoritative; wiped+rebuilt each sync).
 *   2. engines/sglang-overlay/<hf_id>.yaml — FORK-LOCAL additions the upstream
 *      cookbook will never carry (e.g. the DeepSeek-V4-Flash PPU-ZW810E config).
 *      Deep-merged ONTO the generated block. sync-sglang.mjs never writes/wipes
 *      this tree, so overlays survive re-syncs. If only an overlay exists (no
 *      generated block), it is used on its own.
 *
 * IMPORTANT: engines.vllm is a lightweight descriptor ({ min_version }), NOT the
 * recipe object — CommandBuilder serializes `recipe` for client hydration, and a
 * self-reference would be a circular-JSON crash. vLLM synthesis still reads the
 * recipe's top-level fields; only SGLang reads engines.sglang.
 *
 * @param {any} recipe  parsed recipe carrying `hf_id`
 * @param {{sglangDir?:string, sglangOverlayDir?:string, sglangGuidesDir?:string}} [dirs]
 *   override the source trees (used by tests; defaults to the repo layout)
 * @returns {any} the same recipe, possibly with `engines`/`default_engine`
 */
export function attachEngines(recipe, dirs = {}) {
  const sglangDir = dirs.sglangDir || SGLANG_DIR;
  const sglangOverlayDir = dirs.sglangOverlayDir || SGLANG_OVERLAY_DIR;
  const sglangGuidesDir = dirs.sglangGuidesDir || SGLANG_GUIDES_DIR;

  const hfId = recipe?.hf_id;
  if (!hfId) return recipe;

  const genPath = path.join(sglangDir, `${hfId}.yaml`);
  const ovPath = path.join(sglangOverlayDir, `${hfId}.yaml`);
  const gen = fs.existsSync(genPath) ? yaml.load(fs.readFileSync(genPath, "utf8")) : null;
  const ov = fs.existsSync(ovPath) ? yaml.load(fs.readFileSync(ovPath, "utf8")) : null;
  if (!gen && !ov) return recipe;
  let block = gen && ov ? deepMerge(gen, ov) : (gen || ov);

  // Hand-authored SGLang guides live in a separate tree (sync-sglang.mjs never
  // writes there, so they survive upstream re-syncs). Merge onto the block when
  // present; absent leaves block.guide unset and the UI shows a fallback notice.
  const guidePath = path.join(sglangGuidesDir, `${hfId}.md`);
  if (fs.existsSync(guidePath) && block && typeof block === "object") {
    block.guide = fs.readFileSync(guidePath, "utf8");
  }
  recipe.engines = {
    vllm: { min_version: recipe.model?.min_vllm_version || null },
    sglang: block,
  };
  recipe.default_engine = "vllm";
  return recipe;
}
