import fs from "fs";
import path from "path";
import yaml from "js-yaml";

const SGLANG_DIR = path.join(process.cwd(), "engines", "sglang");
const SGLANG_MANUAL_DIR = path.join(process.cwd(), "engines", "sglang-manual");
const SGLANG_GUIDES_DIR = path.join(process.cwd(), "engines", "sglang-guides");

/**
 * If an SGLang engine block exists for this recipe, attach an `engines` map +
 * `default_engine` to the recipe (mutates and returns it).
 *
 * Block resolution, generated-wins:
 *   1. engines/sglang/<hf_id>.yaml        — GENERATED by sync-sglang.mjs from the
 *      upstream sgl-cookbook snapshot (authoritative; wiped+rebuilt each sync).
 *   2. engines/sglang-manual/<hf_id>.yaml — HAND-AUTHORED fallback for models the
 *      upstream cookbook doesn't cover yet. sync-sglang.mjs never writes or wipes
 *      this tree, so manual blocks survive re-syncs. Once upstream starts
 *      covering a model, its generated block supersedes the (now-redundant)
 *      manual one — clean it up when that happens.
 *
 * IMPORTANT: engines.vllm is a lightweight descriptor ({ min_version }), NOT the
 * recipe object — CommandBuilder serializes `recipe` for client hydration, and a
 * self-reference would be a circular-JSON crash. vLLM synthesis still reads the
 * recipe's top-level fields; only SGLang reads engines.sglang.
 *
 * @param {any} recipe  parsed recipe carrying `hf_id`
 * @param {{sglangDir?:string, sglangManualDir?:string, sglangGuidesDir?:string}} [dirs]
 *   override the source trees (used by tests; defaults to the repo layout)
 * @returns {any} the same recipe, possibly with `engines`/`default_engine`
 */
export function attachEngines(recipe, dirs = {}) {
  const sglangDir = dirs.sglangDir || SGLANG_DIR;
  const sglangManualDir = dirs.sglangManualDir || SGLANG_MANUAL_DIR;
  const sglangGuidesDir = dirs.sglangGuidesDir || SGLANG_GUIDES_DIR;

  const hfId = recipe?.hf_id;
  if (!hfId) return recipe;
  let blockPath = path.join(sglangDir, `${hfId}.yaml`);
  if (!fs.existsSync(blockPath)) blockPath = path.join(sglangManualDir, `${hfId}.yaml`);
  if (!fs.existsSync(blockPath)) return recipe;
  const block = yaml.load(fs.readFileSync(blockPath, "utf8"));
  // Hand-authored SGLang guides live in a separate tree (sync-sglang.mjs never
  // writes there, so they survive upstream re-syncs). Merge onto the block when
  // present; absent leaves block.guide unset and the UI shows a fallback notice.
  const guidePath = path.join(sglangGuidesDir, `${hfId}.md`);
  if (fs.existsSync(guidePath) && block && typeof block === "object") {
    block.guide = fs.readFileSync(guidePath, "utf8");
  }
  recipe.engines = {
    vllm: { min_version: recipe.model?.min_vllm_version || null },
    sglang: block,
  };
  recipe.default_engine = "vllm";
  return recipe;
}
