/**
 * Generate engines/sglang/<org>/<repo>.yaml from the vendored upstream
 * (upstream/sglang/) for every model that also has a vLLM recipe (models/).
 *
 * Run after scripts/fetch-sglang-upstream.mjs. Review the diff before committing.
 */
import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import { transform, HW_NAME_MAP } from "../src/lib/engines/sglang-transform.js";

const ROOT = process.cwd();
const GEN_DIR = path.join(ROOT, "upstream", "sglang", "data", "models", "generated");
const MODELS_DIR = path.join(ROOT, "models");
const OUT_DIR = path.join(ROOT, "engines", "sglang");

// Existing vLLM recipe hf_ids (org/repo from the models/ tree) for overlap.
function recipeHfIds() {
  const ids = new Set();
  for (const org of fs.readdirSync(MODELS_DIR)) {
    const orgDir = path.join(MODELS_DIR, org);
    if (!fs.statSync(orgDir).isDirectory()) continue;
    for (const f of fs.readdirSync(orgDir)) {
      if (f.endsWith(".yaml") || f.endsWith(".yml")) ids.add(`${org}/${f.replace(/\.(yaml|yml)$/, "")}`);
    }
  }
  return ids;
}

// Read every generated/v*/*.yaml as { version, doc }.
function versionDocs() {
  const out = [];
  for (const version of fs.readdirSync(GEN_DIR)) {
    const vDir = path.join(GEN_DIR, version);
    if (!fs.statSync(vDir).isDirectory()) continue;
    for (const f of fs.readdirSync(vDir)) {
      if (!f.endsWith(".yaml")) continue;
      out.push({ version, doc: yaml.load(fs.readFileSync(path.join(vDir, f), "utf8")) });
    }
  }
  return out;
}

const docs = versionDocs();
const { blocks, skipped } = transform({ versionDocs: docs, recipeHfIds: recipeHfIds() });

// Warn about upstream hardware names we don't have a taxonomy mapping for.
const knownHw = new Set(Object.keys(HW_NAME_MAP));
const unmapped = new Set();
for (const { doc } of docs) {
  for (const fam of doc.families || []) for (const m of fam.models || []) {
    for (const hw of Object.keys(m.hardware || {})) if (!knownHw.has(hw)) unmapped.add(hw);
  }
}

// Rewrite the generated tree from scratch so removed-upstream models disappear.
fs.rmSync(OUT_DIR, { recursive: true, force: true });
const HEADER = "# GENERATED by scripts/sync-sglang.mjs — do not edit\n";
for (const { hfId, block } of blocks) {
  const file = path.join(OUT_DIR, `${hfId}.yaml`);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, HEADER + yaml.dump(block, { lineWidth: -1 }));
}

console.log(`✓ SGLang sync: ${blocks.length} blocks generated, ${skipped.length} SGLang-only models skipped (no vLLM recipe)`);
if (skipped.length) console.log(`  skipped: ${skipped.join(", ")}`);
if (unmapped.size) console.log(`  ⚠ unmapped upstream hardware (tp dropped): ${[...unmapped].sort().join(", ")}`);
