/**
 * Generate engines/sglang/<org>/<repo>.yaml from the new SGLang cookbook's
 * declarative configs (vendored under upstream/sglang-configs/ by
 * scripts/fetch-sglang-configs.mjs), for every model that also has a vLLM recipe.
 *
 * Each config carries a variant axis; each variant maps — via modelNames — to a
 * distinct HF checkpoint, hence a distinct recipe. So one config can produce
 * several blocks (deepseek-v4 -> Flash + Pro; lfm2.5 -> the LFM2.5 family).
 * Matching against the recipe set is case-insensitive (upstream sometimes uses a
 * lowercase slug); the block is written at the real recipe hf_id.
 *
 * Run after scripts/fetch-sglang-configs.mjs. Wipes+rebuilds engines/sglang/.
 */
import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import { parseConfigModule, configVariantIds, candidateCheckpoints, configToBlock } from "../src/lib/engines/sglang-transform.js";

const ROOT = process.cwd();
const CONFIGS_DIR = path.join(ROOT, "upstream", "sglang-configs", "docs_new", "src", "snippets", "configs");
const MODELS_DIR = path.join(ROOT, "models");
const OUT_DIR = path.join(ROOT, "engines", "sglang");
const TAXONOMY = path.join(ROOT, "taxonomy.yaml");

// Recipe hf_ids (lowercase → real casing) + authoritative precision per recipe.
function scanRecipes() {
  const byLower = new Map(); // lowercase hf_id -> real hf_id
  const precisionByHfId = new Map();
  for (const org of fs.readdirSync(MODELS_DIR)) {
    const orgDir = path.join(MODELS_DIR, org);
    if (!fs.statSync(orgDir).isDirectory()) continue;
    for (const f of fs.readdirSync(orgDir)) {
      if (!/\.ya?ml$/.test(f)) continue;
      const hfId = `${org}/${f.replace(/\.ya?ml$/, "")}`;
      byLower.set(hfId.toLowerCase(), hfId);
      try {
        const rec = yaml.load(fs.readFileSync(path.join(orgDir, f), "utf8"));
        const p = rec?.variants?.default?.precision;
        if (p) precisionByHfId.set(hfId, p);
      } catch { /* build-recipes-api reports YAML errors separately */ }
    }
  }
  return { byLower, precisionByHfId };
}

function taxonomyHwIds() {
  const taxo = yaml.load(fs.readFileSync(TAXONOMY, "utf8"));
  return new Set(Object.keys(taxo?.hardware_profiles || {}));
}

function listConfigFiles(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const rel of fs.readdirSync(dir, { recursive: true })) {
    const relStr = String(rel);
    if (relStr.endsWith(".jsx") && !relStr.endsWith("-benchmarks.jsx")) out.push(path.join(dir, relStr));
  }
  return out;
}

const { byLower, precisionByHfId } = scanRecipes();
const hwIds = taxonomyHwIds();

// Wipe+rebuild so upstream deletions/renames propagate.
fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

const written = [];
const skipped = [];
for (const file of listConfigFiles(CONFIGS_DIR)) {
  const rel = path.relative(CONFIGS_DIR, file);
  let config;
  try { config = parseConfigModule(fs.readFileSync(file, "utf8")); }
  catch (e) { skipped.push(`${rel} (parse error: ${e.message})`); continue; }

  for (const variantId of configVariantIds(config)) {
    // First candidate checkpoint that matches a vLLM recipe (case-insensitive).
    const matched = candidateCheckpoints(config, variantId).find((c) => byLower.has(c.toLowerCase()));
    if (!matched) { skipped.push(`${rel} [${variantId}] (no matching vLLM recipe)`); continue; }
    const hfId = byLower.get(matched.toLowerCase());

    const block = configToBlock(config, variantId, hfId, precisionByHfId.get(hfId), hwIds);
    const outPath = path.join(OUT_DIR, `${hfId}.yaml`);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, `# GENERATED by scripts/sync-sglang.mjs from the new SGLang cookbook — do not edit\n` + yaml.dump(block, { lineWidth: -1 }));
    written.push(hfId);
  }
}

written.sort();
skipped.sort();
console.log(`✓ SGLang blocks: ${written.length} generated`);
for (const w of written) console.log(`   ${w}`);
if (skipped.length) { console.log(`  skipped ${skipped.length}:`); for (const s of skipped) console.log(`   - ${s}`); }
